### ISSUE TITLE
Getting <Code>34010</Code>

### ISSUE THREAD

**Issue by bhaskardabhi** [exotel/ExotelAPI#2]
I tried using below method with appropriate values but keep getting Unauthorized error
```
 curl -X POST https://<your_api_key>:<your_api_token><subdomain>/v1/Accounts/<your_sid>/Calls/connect \
 -d "From=XXXXX30240" \
 -d "To=XXXXX40682" \
 -d "CallerId=0XXXXXX4890"
```
Response:

```
<?xml version="1.0" encoding="UTF-8"?>
<TwilioResponse>
 <RestException>
  <Status>401</Status>
  <Message>Unauthorized; </Message>
  <Code>34010</Code>
 </RestException>
</TwilioResponse>
```

**Comment by vivekpatel111** [comment]
@bhaskardabhi You can use given documentation for error codes - [Outgoing call to connect two numbers](https://developer.exotel.com/api#call-agent)

**Comment by sarathsp06** [comment]
If this is not a typo
```
https://<your_api_key>:<your_api_token><subdomain>/v1/Accounts/<your_sid>/Calls/connect
```


it is missing `@` . The url should be  

```
https://<your_api_key>:<your_api_token>@<subdomain>/v1/Accounts/<your_sid>/Calls/connect
```

**Comment by bhaskardabhi** [comment]
Sorry, there were two issues:

1) I forgot to add @ before <subdomain>. I didn't see mention of @ in the document. 
2) I was using subdomain for india when my client purchased for Singapore.
